version: "3.7"

services:

  minio-s3:
    image: minio/minio:latest
    container_name: minio-s3
    command: 'minio server /data --console-address :9001 --address :9000'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=adminadmin
      - MINIO_DEFAULT_BUCKETS=default

  spark-brain:
    image: spark-image
    container_name: spark-brain
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data
    environment:
      - SPARK_LOCAL_IP=spark-brain
      - SPARK_WORKLOAD=master
      - SPARK_NETWORK_TIMEOUT=420000  # https://stackoverflow.com/questions/51614559/spark-job-finished-wrote-output-file-but-executor-state-is-killed

  spark-worker:
    image: spark-image
    depends_on: [spark-brain]
    container_name: spark-worker
    ports:
      - "9091:8080"
      - "7000:7000"
    environment:
      - MINIO_ACCESS=admin
      - MINIO_SECRET=adminadmin
      - MINIO_HOST=minio-s3
      - MINIO_PORT=9000
      - SPARK_MASTER=spark://spark-brain:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker
      - SPARK_NETWORK_TIMEOUT=420000  # https://stackoverflow.com/questions/51614559/spark-job-finished-wrote-output-file-but-executor-state-is-killed
    volumes:
      - ./apps:/opt/spark-apps
      - ./data:/opt/spark-data

volumes:
  minio_data:
    driver: local